repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: end-of-file-fixer
        exclude: \.sql
      - id: check-yaml
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: ["isort[pyproject]"]
        exclude: _pb2(_grpc)?\.py
        types:
          - python
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]
        exclude: _pb2(_grpc)?\.py
        types:
          - python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
