# coding: utf-8

"""
    Hatchet API

    The Hatchet API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hatchet_sdk.clients.cloud_rest.models.create_managed_worker_build_config_request import CreateManagedWorkerBuildConfigRequest
from hatchet_sdk.clients.cloud_rest.models.create_managed_worker_runtime_config_request import CreateManagedWorkerRuntimeConfigRequest
from typing import Optional, Set
from typing_extensions import Self

class UpdateManagedWorkerRequest(BaseModel):
    """
    UpdateManagedWorkerRequest
    """ # noqa: E501
    name: Optional[StrictStr] = None
    build_config: Optional[CreateManagedWorkerBuildConfigRequest] = Field(default=None, alias="buildConfig")
    env_vars: Optional[Dict[str, StrictStr]] = Field(default=None, description="A map of environment variables to set for the worker", alias="envVars")
    is_iac: Optional[StrictBool] = Field(default=None, alias="isIac")
    runtime_config: Optional[CreateManagedWorkerRuntimeConfigRequest] = Field(default=None, alias="runtimeConfig")
    __properties: ClassVar[List[str]] = ["name", "buildConfig", "envVars", "isIac", "runtimeConfig"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateManagedWorkerRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of build_config
        if self.build_config:
            _dict['buildConfig'] = self.build_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of runtime_config
        if self.runtime_config:
            _dict['runtimeConfig'] = self.runtime_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateManagedWorkerRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "buildConfig": CreateManagedWorkerBuildConfigRequest.from_dict(obj["buildConfig"]) if obj.get("buildConfig") is not None else None,
            "isIac": obj.get("isIac"),
            "runtimeConfig": CreateManagedWorkerRuntimeConfigRequest.from_dict(obj["runtimeConfig"]) if obj.get("runtimeConfig") is not None else None
        })
        return _obj


